name: Input tests
description: Composite action that executes a Robot Framework with Testingbot test

inputs:
  test_conditions:
    description: "Dictionary"

runs:
  using: 'composite'
  steps:
    - name: Input Tests
      id: input-tests
      shell: bash
      env:
        TZ: Europe/Berlin
        CONDITIONS: ${{ inputs.test_conditions }}
      run: |
        echo $CONDITIONS
