name: Input tests
description: Composite action that executes a Robot Framework with Testingbot test

inputs:
  team:
    description: "Team name for test execution"
    required: true
  robot_variables:
    description: "Injected variables for robot tests"
    required: true
  robot_include_tags:
    description: "Tags for including tests"
    required: true
  robot_exclude_tags:
    description: "Tags for excluding tests"
    required: false
  
outputs:
  team_name: 
    description: 'URL to test results'
    value: ${{ steps.test_results.outputs.TEAM }}

runs:
  using: 'composite'
  steps:
    - name: Input Tests
      id: test_results
      shell: bash
      env:
        TZ: Europe/Berlin
        TEAM: ${{ inputs.team }}
        ROBOT_VARIABLES: ${{inputs.robot_variables}}
        I_TAGS: ${{inputs.robot_include_tags}}
        E_TAGS: ${{inputs.robot_exclude_tags}}

      run: |
        echo "TEAM=$TEAM" >> $GITHUB_OUTPUT
        echo "ROBOT_VARIABLES=$TEAM" >> $GITHUB_OUTPUT
        echo "I_TAGS=$TEAM" >> $GITHUB_OUTPUT
        echo "E_TAGS=$TEAM" >> $GITHUB_OUTPUT
