name: Input tests
description: Composite action that executes a Robot Framework with Testingbot test

inputs:
  test_conditions:
    description: "Dictionary"
    required: true
  robot_variables:
    description: "Dictionary"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Input Tests
      shell: bash
      env:
        TZ: Europe/Berlin
        CONDITIONS: ${{ inputs.test_conditions }}
        VARIABLES: ${{inputs.robot_variables}}
      run: |
        echo $CONDITIONS
