name: Run Robot Framework Test
description: Composite action that executes a Robot Framework test

inputs:
  test_path:
    description: "Team name for test execution"
    required: true
  robot_variables:
    description: "Injected variables for robot tests"
    required: false
  robot_including:
    description: "Tags for including tests"
    required: true
  robot_excluding:
    description: "Tags for excluding tests"
    required: false
  robot_output_path:
    description: "Configurable output directory"
    required: false
    default: results
  robot_retry_failed_count:
    description: "A number of retry count"
    required: false
    default: "1"
  robot_log_level:
    description: "A level defintion of robot test log"
    required: false
    default: ""

outputs:
  buyfulfill_results_url: 
    description: 'URL to test results'
    value: ${{ steps.run_robot_test.outputs.buyfulfill_results_url }}
  mac_results_url: 
    description: 'URL to test results'
    value: ${{ steps.run_robot_test.outputs.mac_results_url }}

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run Robot Framework tests direct retry
      id: run_robot_tests
      uses: faditkim/action-test/.github/actions/robot-test-execution-direct-retry@main
      with:
        exec_env: development
        github_checkout_path: ${{ inputs.github_checkout_path }}
        test_path: ${{ inputs.test_path }}
        robot_variables: ${{ inputs.robot_variables }} # key1:value,key2:value2 format
        robot_including: ${{ inputs.robot_including }} # xANDyORz format
        robot_excluding: ${{ inputs.robot_excluding }} # xANDyORz format
        robot_retry_failed_count: ${{ inputs.robot_retry_failed_count }} # default: 1
        robot_output_path: ${{ inputs.robot_output_path }} # default: results
        robot_log_level: ${{ inputs.robot_log_level }} # default: empty
      continue-on-error: true
  
