name: A Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [buyfulfill, mac]
        include:
          - test: buyfulfill
            robot_variables: asdf,asdf2,asdf3
            i_tag: team:buyfulfill
          - test: mac
            robot_variables: zxcv,zxcv2,zxcv3
            e_tag: team:mac

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Robot Framework tests
        id: run_robot_test
        uses: faditkim/action-test/.github/actions/a-tests@main
        with:
          test_conditions: asdf
