name: A Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [buyfulfill, mac]
        include:
          - test: buyfulfill
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_include_tags: team:buyfulfill
          - test: mac
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_include_tags: team:mac
            robot_exclude_tags: no-run

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Robot Framework tests
        id: run_robot_test
        uses: faditkim/action-test/.github/actions/a-tests@main
        with:
          team: ${{ matrix.test }}
          robot_variables: ${{ matrix.robot_variables }}
          robot_include_tags: ${{ matrix.robot_include_tags }}
          robot_exclude_tags: ${{ matrix.robot_exclude_tags }}

      - name: Show results
        shell: bash
        run: |
          echo ${{steps.run_robot_test.outputs.team_name}}
