name: A Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [buyfulfill, mac]
        include:
            - test: buyfulfill
              robot_variables: asdf,asdf2,asdf3
              i_tag: team:buyfulfill
            - test: mac
              robot_variables: zxcv,zxcv2,zxcv3
              e_tag: team:mac
    permissions:
      contents: read
      id-token: write
    outputs:
      test_results_url: ${{ steps.run_robot_test.outputs.test_results_url }}
      robot_results: ${{ steps.robot-summary.outputs.robot_results }}
      is_robot_success: ${{ steps.robot-summary.outputs.is_robot_success }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: show matrix
        shell: bash
        run: |
            echo ${{ matrix.include }}

      - name: Run Robot Framework tests
        id: run_robot_test
        uses: faditkim/action-test/.github/actions/a-tests@main
        with:
            test_conditions: ${{ matrix.include }}
        continue-on-error: true
