name: Matrix Tests

on:
  issue_comment:
    types: [created]

jobs:
  set-matrix:
    if: ${{ github.event.issue.pull_request && (contains(github.event.comment.body, 'robot')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Build shared matrix
        id: set-matrix
        shell: bash
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          # Comment validation
          ROBOT_COMMAND_REGEXP="^robot[[:space:]]+(all|puc-at|puc-de|puc-pl|puc-nl|ansons)[[:space:]]+([^[:space:]]+).*$"
          if [[ "$COMMENT_BODY" =~ $ROBOT_COMMAND_REGEXP ]]; then
            tenant="${BASH_REMATCH[1]}"
            suite="${BASH_REMATCH[2]}"
            run_if_puc=$([[ "$tenant" =~ puc ]] && echo true  || echo false)
            run_if_ansons=$([[ "$tenant" =~ ansons ]] && echo true  || echo false)
            matrix=$(jq -nc \
              --argjson run_if_puc "$run_if_puc" \
              --argjson run_if_ansons "$run_if_ansons" \
              --arg tenant "$tenant" \
              --arg suite "$suite" \
              '{
                build: ["puc", "ansons"],
                include: [
                  {build: "puc", app: "puc_de", environment: "pr", run_if: ($run_if_puc | tostring), tenant: $tenant, suite: $suite},
                  {build: "ansons", app: "ansons", environment: "pr", run_if: ($run_if_ansons | tostring), tenant: $tenant, suite: $suite}
                ]
              }')
            echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi