name: Robot Universal Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World!
        shell: bash
        run: |
          echo "Hello World"

  robot-tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [buyfulfill, mac]
        include:
          - test: buyfulfill
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_including: team:buyfulfillANDsuite:asdfasdf
            robot_output_path: results/buy
          - test: mac
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_including: team:mac
            robot_excluding: no-run
            robot_output_path: results/mac
            robot_retry_listner_usage: "true"
            robot_retry_failed_count: 1

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Formatting Robot Framework options
        id: foramt_robot_options
        uses: faditkim/action-test/.github/actions/format-robot-test-options@main
        with: 
          test_domain: ${{ matrix.test }}
          robot_variables: ${{ matrix.robot_variables }}
          robot_including: ${{ matrix.robot_including }}
          robot_excluding: ${{ matrix.robot_excluding }}
          robot_output_path: ${{ matrix.robot_output_path }}
          robot_retry_failed_count: ${{ matrix.robot_retry_failed_count }}

      - name: Run Robot Framework tests
        id: run_robot_test
        uses: faditkim/action-test/.github/actions/robot-test-execution-direct-retry@main
        with:
          github_checkout_path: .
          test_domain: ${{ steps.format_robot_options.outputs.test }}
          robot_variables: ${{ matrix.robot_variables }}
          robot_including: ${{ matrix.robot_including }}
          robot_excluding: ${{ matrix.robot_excluding }}
          robot_output_path: ${{ matrix.robot_output_path }}
          robot_retry_failed_count: ${{ matrix.robot_retry_failed_count }}

      # - name: Run Robot Framework tests
      #   id: run_robot_test
      #   uses: faditkim/action-test/.github/actions/robot-test-execution-post-retry@main
      #   with:
      #     github_checkout_path: .
      #     test_domain: ${{ matrix.test }}
      #     robot_variables: ${{ matrix.robot_variables }}
      #     robot_including: ${{ matrix.robot_including }}
      #     robot_excluding: ${{ matrix.robot_excluding }}
      #     robot_output_path: ${{ matrix.robot_output_path }}
      #     robot_retry_failed_count: ${{ matrix.robot_retry_failed_count }}
  
  finalize:
    needs: robot-tests
    runs-on: ubuntu-latest
    steps:
      - name: Bye World!
        shell: bash
        run: |
          echo "Bye World"
