name: A Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World!
        shell: bash
        run: |
          echo "Hello World"

  robot-tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [buyfulfill, mac]
        include:
          - test: buyfulfill
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_including_tag: team:buyfulfill
            robot_output_dir: buyfulfill
          - test: mac
            robot_variables: COUNTRY:Germany,TEST_RUN_URL:www.asdf.com
            robot_including_tag: team:mac
            robot_excluding_tag: no-run
            robot_output_dir: mac

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Robot Framework tests
        id: run_robot_test
        uses: faditkim/action-test/.github/actions/universal-robot-test@main
        with:
          github_checkout_path: .
          test_path: ${{ matrix.test }}
          robot_variables: ${{ matrix.robot_variables }}
          robot_including_tag: ${{ matrix.robot_including_tags }}
          robot_excluding_tag: ${{ matrix.robot_excluding_tags }}
          robot_output_dir: ${{ matrix.robot_output_dir }}  
          robot_retry_listner_usage: "true"
          robot_retry_failed_count: 1
  
  finalize:
    needs: robot-tests
    runs-on: ubuntu-latest
    steps:
      - name: Bye World!
        shell: bash
        run: |
          echo "Bye World"
